"""add_resume_verifications_table

Revision ID: 73f9581be055
Revises: 5614cadc1c13
Create Date: 2026-08-09 23:30:01.486427

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '73f9581be055'
down_revision: Union[str, None] = '5614cadc1c13'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('resume_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resume_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('skip_reason', sa.String(length=255), nullable=True),
    sa.Column('resume_skills_count', sa.Integer(), nullable=True),
    sa.Column('matched_count', sa.Integer(), nullable=True),
    sa.Column('unmatched_count', sa.Integer(), nullable=True),
    sa.Column('verification_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('matched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('unmatched_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['resume_id'], ['resumes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_resume_verifications_id'), 'resume_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_resume_verifications_resume_id'), 'resume_verifications', ['resume_id'], unique=False)
    op.create_index(op.f('ix_resume_verifications_user_id'), 'resume_verifications', ['user_id'], unique=False)
    op.alter_column('assessment_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('assessment_sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_resume_verifications_user_id'), table_name='resume_verifications')
    op.drop_index(op.f('ix_resume_verifications_resume_id'), table_name='resume_verifications')
    op.drop_index(op.f('ix_resume_verifications_id'), table_name='resume_verifications')
    op.drop_table('resume_verifications')
    # ### end Alembic commands ###
