"""Add Blueprint models

Revision ID: c3e0353e9170
Revises: e3f4a5b6c7d8
Create Date: 2026-08-12 22:14:11.936504

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c3e0353e9170'
down_revision: Union[str, None] = 'e3f4a5b6c7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blueprints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hackathon_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('domains', postgresql.ARRAY(sa.String(length=50)), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FORMING', 'FULL', 'LOCKED', name='blueprintstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprints_hackathon_id'), 'blueprints', ['hackathon_id'], unique=False)
    op.create_index(op.f('ix_blueprints_id'), 'blueprints', ['id'], unique=False)
    op.create_index(op.f('ix_blueprints_owner_id'), 'blueprints', ['owner_id'], unique=False)
    op.create_table('blueprint_join_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='blueprintjoinrequeststatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_id', 'user_id', name='uq_blueprint_join_request_user')
    )
    op.create_index(op.f('ix_blueprint_join_requests_blueprint_id'), 'blueprint_join_requests', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_blueprint_join_requests_id'), 'blueprint_join_requests', ['id'], unique=False)
    op.create_index(op.f('ix_blueprint_join_requests_user_id'), 'blueprint_join_requests', ['user_id'], unique=False)
    op.create_table('blueprint_slots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('slot_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'FILLED', name='slotstatus'), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blueprint_slots_blueprint_id'), 'blueprint_slots', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_blueprint_slots_id'), 'blueprint_slots', ['id'], unique=False)
    op.create_table('blueprint_invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('receiver_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', 'EXPIRED', name='blueprintinvitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['blueprint_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_id', 'receiver_id', 'slot_id', name='uq_blueprint_invitation')
    )
    op.create_index(op.f('ix_blueprint_invitations_blueprint_id'), 'blueprint_invitations', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_blueprint_invitations_id'), 'blueprint_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_blueprint_invitations_receiver_id'), 'blueprint_invitations', ['receiver_id'], unique=False)
    op.create_index(op.f('ix_blueprint_invitations_sender_id'), 'blueprint_invitations', ['sender_id'], unique=False)
    op.create_index(op.f('ix_blueprint_invitations_slot_id'), 'blueprint_invitations', ['slot_id'], unique=False)
    op.create_table('blueprint_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('blueprint_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=True),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='blueprintmemberrole'), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['blueprint_slots.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blueprint_id', 'user_id', name='uq_blueprint_member_user')
    )
    op.create_index(op.f('ix_blueprint_members_blueprint_id'), 'blueprint_members', ['blueprint_id'], unique=False)
    op.create_index(op.f('ix_blueprint_members_id'), 'blueprint_members', ['id'], unique=False)
    op.create_index(op.f('ix_blueprint_members_slot_id'), 'blueprint_members', ['slot_id'], unique=False)
    op.create_index(op.f('ix_blueprint_members_user_id'), 'blueprint_members', ['user_id'], unique=False)
    op.create_table('blueprint_slot_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slot_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['slot_id'], ['blueprint_slots.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slot_id', 'skill_id', name='uq_blueprint_slot_skill')
    )
    op.create_index(op.f('ix_blueprint_slot_skills_id'), 'blueprint_slot_skills', ['id'], unique=False)
    op.create_index(op.f('ix_blueprint_slot_skills_skill_id'), 'blueprint_slot_skills', ['skill_id'], unique=False)
    op.create_index(op.f('ix_blueprint_slot_skills_slot_id'), 'blueprint_slot_skills', ['slot_id'], unique=False)
    op.alter_column('candidate_profiles', 'profile_strength',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('candidate_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_constraint('candidate_profiles_user_id_key', 'candidate_profiles', type_='unique')
    op.drop_index('ix_candidate_profiles_user_id', table_name='candidate_profiles')
    op.create_index(op.f('ix_candidate_profiles_user_id'), 'candidate_profiles', ['user_id'], unique=True)
    op.alter_column('team_invitations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='invitationstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_team_invitations_receiver_status', table_name='team_invitations')
    op.alter_column('team_join_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='joinrequeststatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_join_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('OWNER', 'MEMBER', name='teammemberrole'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('team_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teams', 'domains',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teams', 'max_members',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teams', 'status',
               existing_type=postgresql.ENUM('OPEN', 'FULL', 'LOCKED', name='teamstatus'),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teams', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('teams', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('teams', 'status',
               existing_type=postgresql.ENUM('OPEN', 'FULL', 'LOCKED', name='teamstatus'),
               server_default=sa.text("'OPEN'::teamstatus"),
               existing_nullable=False)
    op.alter_column('teams', 'max_members',
               existing_type=sa.INTEGER(),
               server_default=sa.text('4'),
               existing_nullable=False)
    op.alter_column('teams', 'domains',
               existing_type=postgresql.ARRAY(sa.VARCHAR(length=50)),
               server_default=sa.text("'{}'::character varying[]"),
               existing_nullable=False)
    op.alter_column('team_members', 'joined_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('team_members', 'role',
               existing_type=postgresql.ENUM('OWNER', 'MEMBER', name='teammemberrole'),
               server_default=sa.text("'MEMBER'::teammemberrole"),
               existing_nullable=False)
    op.alter_column('team_join_requests', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('team_join_requests', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', name='joinrequeststatus'),
               server_default=sa.text("'PENDING'::joinrequeststatus"),
               existing_nullable=False)
    op.create_index('ix_team_invitations_receiver_status', 'team_invitations', ['receiver_id', 'status'], unique=False)
    op.alter_column('team_invitations', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('team_invitations', 'status',
               existing_type=postgresql.ENUM('PENDING', 'ACCEPTED', 'REJECTED', 'CANCELLED', name='invitationstatus'),
               server_default=sa.text("'PENDING'::invitationstatus"),
               existing_nullable=False)
    op.drop_index(op.f('ix_candidate_profiles_user_id'), table_name='candidate_profiles')
    op.create_index('ix_candidate_profiles_user_id', 'candidate_profiles', ['user_id'], unique=False)
    op.create_unique_constraint('candidate_profiles_user_id_key', 'candidate_profiles', ['user_id'])
    op.alter_column('candidate_profiles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('candidate_profiles', 'profile_strength',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_index(op.f('ix_blueprint_slot_skills_slot_id'), table_name='blueprint_slot_skills')
    op.drop_index(op.f('ix_blueprint_slot_skills_skill_id'), table_name='blueprint_slot_skills')
    op.drop_index(op.f('ix_blueprint_slot_skills_id'), table_name='blueprint_slot_skills')
    op.drop_table('blueprint_slot_skills')
    op.drop_index(op.f('ix_blueprint_members_user_id'), table_name='blueprint_members')
    op.drop_index(op.f('ix_blueprint_members_slot_id'), table_name='blueprint_members')
    op.drop_index(op.f('ix_blueprint_members_id'), table_name='blueprint_members')
    op.drop_index(op.f('ix_blueprint_members_blueprint_id'), table_name='blueprint_members')
    op.drop_table('blueprint_members')
    op.drop_index(op.f('ix_blueprint_invitations_slot_id'), table_name='blueprint_invitations')
    op.drop_index(op.f('ix_blueprint_invitations_sender_id'), table_name='blueprint_invitations')
    op.drop_index(op.f('ix_blueprint_invitations_receiver_id'), table_name='blueprint_invitations')
    op.drop_index(op.f('ix_blueprint_invitations_id'), table_name='blueprint_invitations')
    op.drop_index(op.f('ix_blueprint_invitations_blueprint_id'), table_name='blueprint_invitations')
    op.drop_table('blueprint_invitations')
    op.drop_index(op.f('ix_blueprint_slots_id'), table_name='blueprint_slots')
    op.drop_index(op.f('ix_blueprint_slots_blueprint_id'), table_name='blueprint_slots')
    op.drop_table('blueprint_slots')
    op.drop_index(op.f('ix_blueprint_join_requests_user_id'), table_name='blueprint_join_requests')
    op.drop_index(op.f('ix_blueprint_join_requests_id'), table_name='blueprint_join_requests')
    op.drop_index(op.f('ix_blueprint_join_requests_blueprint_id'), table_name='blueprint_join_requests')
    op.drop_table('blueprint_join_requests')
    op.drop_index(op.f('ix_blueprints_owner_id'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_id'), table_name='blueprints')
    op.drop_index(op.f('ix_blueprints_hackathon_id'), table_name='blueprints')
    op.drop_table('blueprints')
    # ### end Alembic commands ###
