"""Change skill_id to name in BlueprintSlotSkill

Revision ID: cfcb3149fc67
Revises: c3e0353e9170
Create Date: 2026-08-12 22:21:41.253772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfcb3149fc67'
down_revision: Union[str, None] = 'c3e0353e9170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprint_slot_skills', sa.Column('name', sa.String(length=255), nullable=False))
    op.drop_index('ix_blueprint_slot_skills_skill_id', table_name='blueprint_slot_skills')
    op.drop_constraint('uq_blueprint_slot_skill', 'blueprint_slot_skills', type_='unique')
    op.create_unique_constraint('uq_blueprint_slot_skill', 'blueprint_slot_skills', ['slot_id', 'name'])
    op.drop_constraint('blueprint_slot_skills_skill_id_fkey', 'blueprint_slot_skills', type_='foreignkey')
    op.drop_column('blueprint_slot_skills', 'skill_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blueprint_slot_skills', sa.Column('skill_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key('blueprint_slot_skills_skill_id_fkey', 'blueprint_slot_skills', 'skills', ['skill_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_blueprint_slot_skill', 'blueprint_slot_skills', type_='unique')
    op.create_unique_constraint('uq_blueprint_slot_skill', 'blueprint_slot_skills', ['slot_id', 'skill_id'])
    op.create_index('ix_blueprint_slot_skills_skill_id', 'blueprint_slot_skills', ['skill_id'], unique=False)
    op.drop_column('blueprint_slot_skills', 'name')
    # ### end Alembic commands ###
